### PR TITLE
Allow local debug by adding endpoint configuration option

### PR DESCRIPTION
**Pull request by manuelbcd**

### CODE REVIEW

**Comment by manuelbcd** [comment]
@seferov The build fails seem to be related with PHP7 deprecations not related with my commits.  Could you confirm please?

**Comment by seferov** [comment]
@manuelbcd you may be right. It is not related to your changes. I will check it.

**Comment by seferov** [comment]
@manuelbcd can you please update the branch with the latest master?
https://github.com/seferov/awsBundle/pull/16 should fix the fail.

**Comment by manuelbcd** [comment]
@seferov  sure.  just merged and pull request sent

Regards

**Comment by manuelbcd** [comment]
@seferov all tests passed ;)

**Comment by manuelbcd** [comment]
@seferov Is everything ok?

**Comment by seferov** [comment]
thank you!

**Pull request merged**
